export enum MainActionsTypes{
    SET_ASSETS_LIST = '@@MAIN/SET_ASSETS_LIST',
    SET_POOLS_LIST = '@@MAIN/SET_POOLS_LIST',


    LOAD_PARAMS = '@@MAIN/LOAD_PARAMS',
    LOAD_PARAMS_SUCCESS = '@@MAIN/LOAD_PARAMS_SUCCESS',
    LOAD_PARAMS_FAILURE = '@@MAIN/LOAD_PARAMS_FAILURE',


    LOAD_POOLS_LIST = '@@MAIN/LOAD_POOLS_LIST',
    LOAD_POOLS_LIST_SUCCESS = '@@MAIN/LOAD_POOLS_LIST_SUCCESS',
    LOAD_POOLS_LIST_FAILURE = '@@MAIN/LOAD_POOLS_LIST_FAILURE',

    SET_TX_STATUS = '@@MAIN/SET_TX_STATUS',
}
